name: onboarding
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  easy_localization: ^3.0.1
  either_dart: ^0.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_secure_storage: ^6.0.0
  flutter_svg: ^1.1.5
  freezed_annotation: ^2.2.0
  go_router: ^5.0.5
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  json_annotation: ^4.7.0
  provider: ^6.0.4

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.0
  dart_code_metrics: ^4.19.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  json_serializable: ^6.5.2
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  assets:
   - resources/
   - resources/icons/
   - resources/images/
   - resources/translations/
